import './Popup.scss';
import linkStyles from './link.module.scss';
import { updateState } from '../management/store';
import { useExtensionState } from '../shared/hooks/useExtensionState';

export const Popup = () => {
  const state = useExtensionState();
  const link = 'https://github.com/guocaoyi/create-chrome-ext';

  const minus = () => {
    if (state.counter === 0) return;
    updateState({
      counter: state.counter - 1
    });
  };

  const add = () => {
    updateState({
      counter: state.counter + 1
    });
  };

  return (
    <main>
      <h3>Popup Page</h3>
      <div className="calc">
        <button onClick={minus} disabled={state.counter <= 0}>
          -
        </button>
        <label>{state.counter}</label>
        <button onClick={add}>+</button>
      </div>
      <a
        href={link}
        target="_blank"
        rel="noreferrer"
        className={linkStyles.testOne}
      >
        generated by create-chrome-ext
      </a>
    </main>
  );
};

export default Popup;
