import './Options.scss';

export const Options = () => {
  const link = 'https://github.com/guocaoyi/create-chrome-ext';

  return (
    <main>
      <h3>Options Page</h3>
      <h4>Count from Popup: {counter}</h4>
      <a href={link} target="_blank" rel="noreferrer">
        generated by create-chrome-ext
      </a>
    </main>
  );
};

export default Options;
