import { useExtensionState } from '../shared/hooks/useExtensionState';
import { UsersContainer } from '../modules/UsersContainer';
import * as S from './styles';

export const SidePanel = () => {
  const state = useExtensionState();
  const link = 'https://github.com/guocaoyi/create-chrome-ext';

  return (
    <S.Container>
      <h3>SidePanel Page</h3>
      <h4>Count from Popup: {state.counter}</h4>
      <a href={link} target="_blank" rel="noreferrer">
        generated by create-chrome-ext
      </a>
      <p>token: {state.user.token}</p>
      <p>user: {state.user.user}</p>
      <p>password: {state.user.password}</p>
      <br />
      <UsersContainer />
    </S.Container>
  );
};

export default SidePanel;
